### PR TITLE
Fix "apt-add-repository: command not found"

### PR DESCRIPTION
**Pull request by perfectfoolish**
ENV: aliyun ubuntu 12.04 64

### CODE REVIEW

**Comment by chloerei** [comment]
Recommend system is Ubuntu 14.04, no plan to maintain two versions, so your should fix it in your own branch.

And you should change passenger repo to 12.04 too.

**Comment by perfectfoolish** [comment]
Thx, readme still tell 12.04, should update the info about system, i will change sys to 14.04

**Comment by chloerei** [comment]
Ok, updated.

**Comment by perfectfoolish** [comment]
now i use Ubuntu 14.04.1 LTS , also have this question

**Comment by perfectfoolish** [comment]
This time use "sudo apt-get install software-properties-common" to solve the problem.

**Pull request closed without merging**
